//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosComida.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_aba1b3_pedidoscomidaEntities : DbContext
    {
        public db_aba1b3_pedidoscomidaEntities()
            : base("name=db_aba1b3_pedidoscomidaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblCarrito> tblCarrito { get; set; }
        public virtual DbSet<tblPedido> tblPedido { get; set; }
        public virtual DbSet<tblProducto> tblProducto { get; set; }
    }
}
