//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosComida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducto()
        {
            this.tblCarrito = new HashSet<tblCarrito>();
        }

        public int ID_Producto { get; set; }

        [Required(ErrorMessage = "El nombre del producto es obligatorio.")]
        [StringLength(50, ErrorMessage = "El nombre no puede exceder los 50 caracteres.")]
        [Display(Name = "Nombre del producto")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "El precio es obligatorio.")]
        [Range(1, 1000, ErrorMessage = "El precio debe estar entre 1 y 1,000.")]
        [Display(Name = "Precio")]
        public Nullable<decimal> Precio { get; set; }

        [Required(ErrorMessage = "La categoría es obligatoria.")]
        [StringLength(50, ErrorMessage = "La categoría no puede exceder los 50 caracteres.")]
        [Display(Name = "Categoría")]
        public string Categoria { get; set; }

        [StringLength(250, ErrorMessage = "La URL de la imagen no puede exceder los 250 caracteres.")]
        [Url(ErrorMessage = "La URL de la imagen no es válida.")]
        [Display(Name = "URL de imagen")]
        public string ImagenURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCarrito> tblCarrito { get; set; }
    }
}
